# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import check as module_0


def test_case_0():
    command_0 = module_0.Command()
    assert module_0.Command.requires_project is True
    assert module_0.Command.default_settings == {"LOG_ENABLED": False}


def test_case_1():
    command_0 = module_0.Command()
    assert module_0.Command.requires_project is True
    assert module_0.Command.default_settings == {"LOG_ENABLED": False}
    var_0 = command_0.syntax()
    assert var_0 == "[options] <spider>"


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    command_0 = module_0.Command()
    assert module_0.Command.requires_project is True
    assert module_0.Command.default_settings == {"LOG_ENABLED": False}
    var_0 = command_0.short_desc()
    assert var_0 == "Check spider contracts"
    var_0.printErrorList(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    command_0 = module_0.Command()
    assert module_0.Command.requires_project is True
    assert module_0.Command.default_settings == {"LOG_ENABLED": False}
    command_1 = module_0.Command()
    command_1.add_options(command_1)
