# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import check_typed as module_0


def test_case_0():
    command_0 = module_0.Command()
    assert module_0.Command.default_settings == {"LOG_ENABLED": False}


@pytest.mark.xfail(strict=True)
def test_case_1():
    command_0 = module_0.Command()
    assert module_0.Command.default_settings == {"LOG_ENABLED": False}
    float_0 = -1319.8602
    str_0 = command_0.syntax()
    assert str_0 == "[options] <spider>"
    command_0.add_options(float_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    command_0 = module_0.Command()
    assert module_0.Command.default_settings == {"LOG_ENABLED": False}
    var_0 = command_0.long_desc()
    assert var_0 == "Check spider contracts"
    var_0.from_spider(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    command_0 = module_0.Command()
    assert module_0.Command.default_settings == {"LOG_ENABLED": False}
    command_1 = module_0.Command()
    command_0.add_options(command_0)
